### ISSUE TITLE
What tool are you using to debug pytorch

### ISSUE THREAD

**Issue by HongLouyemeng** [nicknytko/numml#14]
How did you debug the .CPP and .py.  vscode or gpd , or other tool QAQ?

**Comment by nicknytko** [comment]
Hi! I've mostly been sticking to debugging the C++ code with GDB and the CUDA debugger.  Writing tests has also been helpful to make sure everything is working properly.  Are you running into issues trying to run/install?

**Comment by HongLouyemeng** [comment]
> Hi! I've mostly been sticking to debugging the C++ code with GDB and the CUDA debugger. Writing tests has also been helpful to make sure everything is working properly. Are you running into issues trying to run/install?

yes,I built torch with pytorch debug=1 and  using [Python C++ Debugger](https://marketplace.visualstudio.com/items?itemName=benjamin-simmonds.pythoncpp-debug)  to debug the torch.distributed.allreduce and torch.distributed.ProcessGroupGloo.cpp's **allreduce** , but debug can't get past the **dist.allreduce()** into ProcessGroupGloo.cpp's breakpoints

**Comment by nicknytko** [comment]
Does it work if you try running from the command line with gdb?  Something like `gdb --args python3 script.py`, then set the breakpoint normally.  I don't have too much experience with using VSCode, unfortunately.

**Comment by HongLouyemeng** [comment]
> Does it work if you try running from the command line with gdb? Something like `gdb --args python3 script.py`, then set the breakpoint normally. I don't have too much experience with using VSCode, unfortunately.

I haven't tried this before, thank you for sharing your experience OVO

**Comment by nicknytko** [comment]
Sure -- I'm closing this issue but feel free to continue following up in a discussion (https://github.com/nicknytko/numml/discussions/landing)
